apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: americana-backend
  labels: 
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: americanasecretkey1
      containers:
      - name: users-service-cont
        image: {{Users_image}}
        imagePullPolicy: Always
      - name: auth-service-cont
        image: {{Auth_image}}
        imagePullPolicy: Always
      - name: menu-service-cont
        image: {{Menu_image}}
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: americana-backend-service
spec:
  selector:
    app: americana-backend
  ports:
  - protocol: TCP
    port: 80