apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: auth-service
        image: {{Auth_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: api
        - containerPort: 50051
          name: grpc-auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000

---
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-auth
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051

---

apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: user-service
        image: {{Users_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4001
        - containerPort: 50052
          name: grpc-user
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-user
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50052
---

apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: menu-service
  labels:
    app: menu-service
spec:
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: menu-service
        image: {{Menu_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4002
        - containerPort: 50053
          name: grpc-menu
---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
spec:
  selector:
    app: menu-service
  ports:
  - protocol: TCP
    port: 4002
    targetPort: 4002
---

apiVersion: v1
kind: Service
metadata:
  name: grpc-menu
spec:
  type: LoadBalancer
  selector:
    app: menu-service
  ports:
  - protocol: TCP
    port: 50053
    targetPort: 50053

---

apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: order-service
        image: {{Order_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4003
        - containerPort: 50054
          name: grpc-order
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 4003
    targetPort: 4003
---

apiVersion: v1
kind: Service
metadata:
  name: grpc-order
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 50054
    targetPort: 50054