apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: americana-backend
  labels: 
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: users-service_cont
        image: ${Users_image}

      #- name: auth-service_cont
      #  image: ${Auth_image}

      #- name: Menu-service_cont
      #  image: ${Menu_image}