version: '3.7'
services:

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  kafka:
    build: .
    ports:
      - "9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  aerospikedb:
    image: aerospike/aerospike-server:latest
    networks:
    - aerospikenetwork
    deploy:
        replicas: 2
        endpoint_mode: dnsrr
    labels:
        com.aerospike.cluster: "myproject"
    command: [ "--config-file","/run/secrets/aerospike.conf"]
    secrets:
    - source: conffile
      target: aerospike.conf
      mode: 0440

  auth:
    image: auth
    ports:
      - "4000:4000"
    restart: always
    networks:
      - test-net
    env_file:
      - ./service-registry.env

  user:
    image: user
    ports:
      - "4001:4001"
    restart: always
    networks:
      - test-net
    env_file:
      - ./service-registry.env
    depends_on:
      - auth
      
  menu:
    image: menu
    ports:
      - "4002:4002"
    restart: always
    networks:
      - test-net
    env_file:
      - ./service-registry.env
    depends_on:
      - auth

  nginx:
    image: mynginx
    networks:
      - test-net
    ports:
      - 3080:3080
    command: [nginx, '-g', 'daemon off;']
    env_file:
      - ./service-registry.env
    depends_on:
      - user
      - auth
      - menu

  networks:
    test-net:
      driver: bridge
    aerospikenetwork:
      driver: overlay
      attachable: true