version: '2'
services:

  user:
    image: user-service
    ports:
      - "4000:4000"
    restart: always
    networks:
      - test-net
    env_file:
      - ./service-registry.env
    depends_on:
      - mongo
      - redis
      - aerospike
      
  auth:
    image: auth-service
    ports:
      - "4001:4001"
    restart: always
    networks:
      - test-net
    env_file:
      - ./service-registry.env
      
  menu:
    image: menu-service
    ports:
      - "4002:4002"
    restart: always
    networks:
      - test-net
    env_file:
      - ./service-registry.env
      
  nginx:
    image: mynginx
    networks:
      - test-net
    ports:
      - 3080:3080
    command: [nginx, '-g', 'daemon off;']
    env_file:
      - ./service-registry.env
    depends_on:
      - user
      - auth
      - menu

networks:
  test-net:
    driver: bridge