apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: auth-service
        image: {{Auth_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: api
        - containerPort: 50051
          name: grpc-auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-auth
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051

---

apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: user-service
        image: {{Users_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4001
        - containerPort: 50052
          name: grpc-user
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-user
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50052
---

apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: menu-service
  labels:
    app: menu-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: menu-service
        image: {{Menu_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4002
        - containerPort: 50053
          name: grpc-menu
---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
spec:
  selector:
    app: menu-service
  ports:
  - protocol: TCP
    port: 4002
    targetPort: 4002
---

apiVersion: v1
kind: Service
metadata:
  name: grpc-menu
spec:
  type: LoadBalancer
  selector:
    app: menu-service
  ports:
  - protocol: TCP
    port: 50053
    targetPort: 50053

---

apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: order-service
        image: {{Order_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4003
        - containerPort: 50054
          name: grpc-order
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 4003
    targetPort: 4003
---

apiVersion: v1
kind: Service
metadata:
  name: grpc-order
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 50054
    targetPort: 50054
    
---
apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: deeplink-service
  labels:
    app: deeplink-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deeplink-service
  template:
    metadata:
      labels:
        app: deeplink-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: deeplink-service
        image: {{Deeplink_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4005
          name: api
        - containerPort: 50056
          name: grpc-deeplink

---
apiVersion: v1
kind: Service
metadata:
  name: deeplink-service
spec:
  selector:
    app: deeplink-service
  ports:
  - protocol: TCP
    port: 4005
    targetPort: 4005

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-deeplink
spec:
  type: LoadBalancer
  selector:
    app: deeplink-service
  ports:
  - protocol: TCP
    port: 50056
    targetPort: 50056
---
apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: kafka-service
  labels:
    app: kafka-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-service
  template:
    metadata:
      labels:
        app: kafka-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: kafka-service
        image: {{Kafka_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4006
          name: api
        - containerPort: 50057
          name: grpc-kafka
          
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-service
  ports:
  - protocol: TCP
    port: 4006
    targetPort: 4006

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-kafka
spec:
  type: LoadBalancer
  selector:
    app: kafka-service
  ports:
  - protocol: TCP
    port: 50057
    targetPort: 50057
---
apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: sync-service
  labels:
    app: sync-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sync-service
  template:
    metadata:
      labels:
        app: sync-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: sync-service
        image: {{Sync_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4004
          name: api
        - containerPort: 50055
          name: grpc-sync
---
apiVersion: v1
kind: Service
metadata:
  name: sync-service
spec:
  selector:
    app: sync-service
  ports:
  - protocol: TCP
    port: 4004
    targetPort: 4004

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-sync
spec:
  type: LoadBalancer
  selector:
    app: sync-service
  ports:
  - protocol: TCP
    port: 50055
    targetPort: 50055
---
apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: location-service
  labels:
    app: location-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      imagePullSecrets:
      - name: americanasecret
      containers:
      - name: location-service
        image: {{Location_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4007
          name: api
        - containerPort: 50058
          name: grpc-location
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
spec:
  selector:
    app: location-service
  ports:
  - protocol: TCP
    port: 4007
    targetPort: 4007

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-location
spec:
  type: LoadBalancer
  selector:
    app: location-service
  ports:
  - protocol: TCP
    port: 50058
    targetPort: 50058