apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nodeapp
  namespace: nodeapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-hostname: localhost
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    appgw.ingress.kubernetes.io/backend-protocol: http
    
spec:
  tls:
  - hosts:
    - mobapi.americana-food.com
    secretName: mobapi-secret
  rules:
  - host: mobapi.americana-food.com
  - http:
      paths:
      - backend:
          serviceName: auth-service
          servicePort: 4000
        path: /auth-service/*
      - backend:
          serviceName: user-service
          servicePort: 4001
        path: /user-service/*
      - backend:
          serviceName: menu-service
          servicePort: 4002
        path: /menu-service/*
      - backend:
          serviceName: order-service
          servicePort: 4003
        path: /order-service/*
      - backend:
          serviceName: deeplink-service
          servicePort: 4005
        path: /deeplink-service/*
      - backend:
          serviceName: kafka-service
          servicePort: 4006
        path: /kafka-service/*
      - backend:
          serviceName: sync-service
          servicePort: 4004
        path: /sync-service/*
      - backend:
          serviceName: location-service
          servicePort: 4007
        path: /location-service/*
      - backend:
          serviceName: notification-service
          servicePort: 4008
        path: /notification-service/*
      - backend:
          serviceName: payment-service
          servicePort: 4009
        path: /payment-service/*
      - backend:
          serviceName: promotion-service
          servicePort: 4010
        path: /promotion-service/*
      - backend:
          serviceName: upload-service
          servicePort: 4011
        path: /upload-service/*
      - backend:
          serviceName: log-service
          servicePort: 4012
        path: /log-service/*
      - backend:
          serviceName: home-service
          servicePort: 4013
        path: /home-service/*
